### PR TITLE
adds retrieval logic

### PR DESCRIPTION
**Pull request by koleshjr**
adds retrieval logic using LCEL
If any changes is required please let me know.
Thank you

### CODE REVIEW

**Review by KevKibe — CHANGES_REQUESTED** [review]
Thanks for the PR.
Everything, checks out, don't mind the failed tests, I'll run the tests with my environment variables.
Is there a dependency that needs to be added to use 
`from operator import itemgetter` and `from langchain_core.prompts import PromptTemplate` imports, if there is kindly add them to the PR in both `requirements.txt` and `setup.cfg`.
And could you remove one import of `from langchain_pinecone import PineconeVectorStore` module, it's imported twice in both files.

**Comment by koleshjr** [comment]
yeah only for langchain core though  , I'm on my way home. will fix when I get home

**Comment by koleshjr** [comment]
Fixed it. 
Added some flexibility to the retieve method by letting the user specify the models they want 
But also adding default models incase they don't provide it
I have not tested them yet, Kindly test and lemme know if there are issues I need to fix

Thanks

**Review by KevKibe — APPROVED** [review]
LGTM

**Comment by KevKibe** [comment]
PR Merged🥳

**Comment by koleshjr** [comment]
🥳🥳🥳🥳

**Comment by koleshjr** [comment]
rerankers next. Still reading about them.

**Comment by koleshjr** [comment]
Btw kindly test the method. I just noticed a bug 

retriever = vector_store.as_retriver(search_kwargs = {"k": top_k})

fix the above in both openai and google to :

retriever = vector_store.as_retriever(search_kwargs = {"k": top_k})

missed the e in the retriever

**Comment by KevKibe** [comment]
Nice.
I'm adding support for cohere embeddings and then do some tests to make sure everything works well, then I draft a release.

**Comment by koleshjr** [comment]
great

**Pull request merged**
